export const bankLists = [
  { label: "Agrani Bank Plc", value: "AGRANI_BANK_PLC" },
  { label: "Janata Bank Plc", value: "JANATA_BANK_PLC" },
  { label: "Sonali Bank Plc", value: "SONALI_BANK_PLC" },
  { label: "Rupali Bank Plc", value: "RUPALI_BANK_PLC" },
  { label: "Bangladesh Development Bank Plc", value: "BANGLADESH_DEVELOPMENT_BANK_PLC" },
  { label: "Basic Bank Limited", value: "BASIC_BANK_LIMITED" },
  { label: "Bangladesh Krishi Bank", value: "BANGLADESH_KRISHI_BANK" },
  { label: "Rajshahi Krishi Unnayan Bank", value: "RAJSHAHI_KRISHI_UNNAYAN_BANK" },
  { label: "Probashi Kallyan Bank", value: "PROBASHI_KALLYAN_BANK" },
  { label: "Ab Bank Plc", value: "AB_BANK_PLC" },
  { label: "Bangladesh Commerce Bank Limited", value: "BANGLADESH_COMMERCE_BANK_LIMITED" },
  { label: "Bank Asia Plc", value: "BANK_ASIA_PLC" },
  { label: "Bengal Commercial Bank Limited", value: "BENGAL_COMMERCIAL_BANK_LIMITED" },
  { label: "Brac Bank Plc", value: "BRAC_BANK_PLC" },
  { label: "City Bank Plc", value: "CITY_BANK_PLC" },
  { label: "Community Bank Bangladesh Plc", value: "COMMUNITY_BANK_BANGLADESH_PLC" },
  { label: "Citizens Bank Plc", value: "CITIZENS_BANK_PLC" },
  { label: "Dhaka Bank Plc", value: "DHAKA_BANK_PLC" },
  { label: "Dhaka Mercantile Co Operative Bank Limited", value: "DHAKA_MERCANTILE_CO_OPERATIVE_BANK_LIMITED" },
  { label: "Dutch Bangla Bank Plc", value: "DUTCH_BANGLA_BANK_PLC" },
  { label: "Eastern Bank Plc", value: "EASTERN_BANK_PLC" },
  { label: "Ific Bank Plc", value: "IFIC_BANK_PLC" },
  { label: "Jamuna Bank Limited", value: "JAMUNA_BANK_LIMITED" },
  { label: "Meghna Bank Plc", value: "MEGHNA_BANK_PLC" },
  { label: "Mercantile Bank Plc", value: "MERCANTILE_BANK_PLC" },
  { label: "Midland Bank Limited", value: "MIDLAND_BANK_LIMITED" },
  { label: "Modhumoti Bank Limited", value: "MODHUMOTI_BANK_LIMITED" },
  { label: "Mutual Trust Bank Plc", value: "MUTUAL_TRUST_BANK_PLC" },
  { label: "National Credit And Commerce Bank Plc", value: "NATIONAL_CREDIT_AND_COMMERCE_BANK_PLC" },
  { label: "Nrb Bank Limited", value: "NRB_BANK_LIMITED" },
  { label: "Nrbcbank Plc", value: "NRBC_BANK_PLC" },
  { label: "One Bank Plc", value: "ONE_BANK_PLC" },
  { label: "Premier Bank Plc", value: "PREMIER_BANK_PLC" },
  { label: "Prime Bank Plc", value: "PRIME_BANK_PLC" },
  { label: "Pubali Bank Plc", value: "PUBALI_BANK_PLC" },
  { label: "Shimanto Bank Limited", value: "SHIMANTO_BANK_LIMITED" },
  { label: "Southeast Bank Limited", value: "SOUTHEAST_BANK_LIMITED" },
  { label: "South Bangla Agriculture And Commerce Bank Limited", value: "SOUTH_BANGLA_AGRICULTURE_AND_COMMERCE_BANK_LIMITED" },
  { label: "Trust Bank Plc", value: "TRUST_BANK_PLC" },
  { label: "United Commercial Bank Plc", value: "UNITED_COMMERCIAL_BANK_PLC" },
  { label: "Uttara Bank Plc", value: "UTTARA_BANK_PLC" },
  { label: "Standard Bank Limited", value: "STANDARD_BANK_LIMITED" },
  { label: "Exim Bank PLC", value: "EXIM_BANK_PLC" },
  { label: "Islami Bank Bangladesh PLC", value: "ISLAMI_BANK_BANGLADESH_PLC" },
  { label: "Al‑Arafah Islami Bank PLC", value: "AL_ARAFAH_ISLAMI_BANK_PLC" },
  { label: "First Security Islami Bank PLC", value: "FIRST_SECURITY_ISLAMI_BANK_PLC" },
  { label: "ICB Islamic Bank PLC", value: "ICB_ISLAMIC_BANK_PLC" },
  { label: "Social Islami Bank PLC", value: "SOCIAL_ISLAMI_BANK_PLC" },
  { label: "Global Islami Bank PLC", value: "GLOBAL_ISLAMI_BANK_PLC" },
  { label: "Union Bank PLC", value: "UNION_BANK_PLC" },
  { label: "Padma Bank PLC", value: "PADMA_BANK_PLC" },
];
