export const bankLists = [
  { label: "AB Bank PLC", value: "AB_BANK_PLC" },
  { label: "Agrani Bank PLC", value: "AGRANI_BANK_PLC" },
  { label: "Al-Arafah Islami Bank PLC", value: "AL-ARAFAH_ISLAMI_BANK_PLC" },
  { label: "BASIC Bank Limited", value: "BASIC_BANK_LIMITED" },
  { label: "BRAC Bank PLC", value: "BRAC_BANK_PLC" },
  {
    label: "Bangladesh Commerce Bank Limited",
    value: "BANGLADESH_COMMERCE_BANK_LIMITED",
  },
  {
    label: "Bangladesh Development Bank PLC",
    value: "BANGLADESH_DEVELOPMENT_BANK_PLC",
  },
  { label: "Bangladesh Krishi Bank", value: "BANGLADESH_KRISHI_BANK" },
  { label: "Bank Al-Falah Limited", value: "BANK_AL-FALAH_LIMITED" },
  { label: "Bank Asia PLC.", value: "BANK_ASIA_PLC" },
  { label: "Bengal Commercial Bank PLC.", value: "BENGAL_COMMERCIAL_BANK_PLC" },
  { label: "Citibank N.A", value: "CITIBANK_NA" },
  { label: "Citizens Bank PLC", value: "CITIZENS_BANK_PLC" },
  { label: "City Bank PLC", value: "CITY_BANK_PLC" },
  {
    label: "Commercial Bank of Ceylon Limited",
    value: "COMMERCIAL_BANK_OF_CEYLON_LIMITED",
  },
  {
    label: "Community Bank Bangladesh PLC.",
    value: "COMMUNITY_BANK_BANGLADESH_PLC",
  },
  { label: "Dhaka Bank PLC", value: "DHAKA_BANK_PLC" },
  { label: "Dutch-Bangla Bank PLC", value: "DUTCH-BANGLA_BANK_PLC" },
  { label: "Eastern Bank PLC", value: "EASTERN_BANK_PLC" },
  {
    label: "Export Import Bank of Bangladesh PLC",
    value: "EXPORT_IMPORT_BANK_OF_BANGLADESH_PLC",
  },
  {
    label: "First Security Islami Bank PLC",
    value: "FIRST_SECURITY_ISLAMI_BANK_PLC",
  },
  { label: "Global Islami Bank PLC", value: "GLOBAL_ISLAMI_BANK_PLC" },
  { label: "Habib Bank Ltd.", value: "HABIB_BANK_LTD" },
  { label: "ICB Islamic Bank Ltd.", value: "ICB_ISLAMIC_BANK_LTD" },
  { label: "IFIC Bank PLC", value: "IFIC_BANK_PLC" },
  { label: "Islami Bank Bangladesh PLC", value: "ISLAMI_BANK_BANGLADESH_PLC" },
  { label: "Jamuna Bank PLC", value: "JAMUNA_BANK_PLC" },
  { label: "Janata Bank PLC", value: "JANATA_BANK_PLC" },
  { label: "Meghna Bank PLC", value: "MEGHNA_BANK_PLC" },
  { label: "Mercantile Bank PLC", value: "MERCANTILE_BANK_PLC" },
  { label: "Midland Bank Limited", value: "MIDLAND_BANK_LIMITED" },
  { label: "Modhumoti Bank PLC", value: "MODHUMOTI_BANK_PLC" },
  { label: "Mutual Trust Bank PLC", value: "MUTUAL_TRUST_BANK_PLC" },
  { label: "National Bank PLC", value: "NATIONAL_BANK_PLC" },
  { label: "National Bank of Pakistan", value: "NATIONAL_BANK_OF_PAKISTAN" },
  {
    label: "National Credit & Commerce Bank PLC",
    value: "NATIONAL_CREDIT_AND_COMMERCE_BANK_PLC",
  },
  { label: "NRB Bank PLC", value: "NRB_BANK_PLC" },
  { label: "NRBC Bank PLC", value: "NRBC_BANK_PLC" },
  { label: "One Bank PLC", value: "ONE_BANK_PLC" },
  { label: "Padma Bank PLC", value: "PADMA_BANK_PLC" },
  { label: "Prime Bank PLC", value: "PRIME_BANK_PLC" },
  { label: "Probashi Kollyan Bank", value: "PROBASHI_KOLLYAN_BANK" },
  { label: "Pubali Bank PLC", value: "PUBALI_BANK_PLC" },
  {
    label: "Rajshahi Krishi Unnayan Bank",
    value: "RAJSHAHI_KRISHI_UNNAYAN_BANK",
  },
  { label: "Rupali Bank PLC", value: "RUPALI_BANK_PLC" },
  { label: "SBAC Bank PLC", value: "SBAC_BANK_PLC" },
  { label: "Shahjalal Islami Bank PLC", value: "SHAHJALAL_ISLAMI_BANK_PLC" },
  { label: "Shimanto Bank PLC", value: "SHIMANTO_BANK_PLC" },
  { label: "Social Islami Bank PLC", value: "SOCIAL_ISLAMI_BANK_PLC" },
  { label: "Sonali Bank PLC", value: "SONALI_BANK_PLC" },
  { label: "Southeast Bank PLC", value: "SOUTHEAST_BANK_PLC" },
  { label: "Standard Bank PLC", value: "STANDARD_BANK_PLC" },
  { label: "Standard Chartered Bank", value: "STANDARD_CHARTERED_BANK" },
  { label: "State Bank of India", value: "STATE_BANK_OF_INDIA" },
  {
    label: "The Hong Kong and Shanghai Banking Corporation. Ltd.",
    value: "THE_HONG_KONG_AND_SHANGHAI_BANKING_CORPORATION_LTD",
  },
  { label: "The Premier Bank PLC", value: "THE_PREMIER_BANK_PLC" },
  { label: "Trust Bank PLC", value: "TRUST_BANK_PLC" },
  { label: "Union Bank PLC", value: "UNION_BANK_PLC" },
  { label: "United Commercial Bank PLC", value: "UNITED_COMMERCIAL_BANK_PLC" },
  { label: "Uttara Bank PLC", value: "UTTARA_BANK_PLC" },
  { label: "Woori Bank", value: "WOORI_BANK" },
];
